# Generated by Django 6.0.5 on 2026-05-17 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate_tzs', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid_tzs', models.DecimalField(decimal_places=2, editable=False, max_digits=30)),
                ('payment_method', models.CharField(choices=[('crdb', 'CRDB Bank'), ('nmb', 'NMB Bank'), ('nbc', 'NBC Bank'), ('equity', 'Equity Bank'), ('absa', 'Absa Bank'), ('stanbic', 'Stanbic Bank'), ('exim', 'Exim Bank'), ('boa', 'BOA Bank'), ('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halopesa', 'HaloPesa'), ('cash', 'Cash')], max_length=20)),
                ('supplier_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate_tzs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lot', to='purchases.purchase')),
            ],
            options={
                'db_table': 'inventory_lots',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='purchases_created_41e89e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier_name'], name='purchases_supplie_93f140_idx'),
        ),
    ]
