# Generated by Django 6.0.5 on 2026-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rate', models.DecimalField(decimal_places=2, default=2000, max_digits=20)),
                ('max_rate', models.DecimalField(decimal_places=2, default=5000, max_digits=20)),
                ('min_asset_value', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('max_asset_value', models.DecimalField(decimal_places=2, default=100000, max_digits=20)),
                ('company_capital', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('report_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
