# Generated by Django 6.0.5 on 2026-05-17 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_rate_tzs', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount_tzs', models.DecimalField(decimal_places=2, max_digits=30)),
                ('avg_buy_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_tzs', models.DecimalField(decimal_places=2, max_digits=30)),
                ('payment_method', models.CharField(choices=[('crdb', 'CRDB Bank'), ('nmb', 'NMB Bank'), ('nbc', 'NBC Bank'), ('equity', 'Equity Bank'), ('absa', 'Absa Bank'), ('stanbic', 'Stanbic Bank'), ('exim', 'Exim Bank'), ('boa', 'BOA Bank'), ('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halopesa', 'HaloPesa'), ('cash', 'Cash')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_consumed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lots', to='purchases.inventorylot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lots', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_lots',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_created_dbdf91_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer_name'], name='sales_custome_1206cf_idx'),
        ),
    ]
